apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "server.spire.fullname" . }}
  labels:
    app: {{ template "spire.name" . }}
    component: server
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  server.conf: |
    server {
        bind_address = "0.0.0.0"
        bind_port = "8081"
        bind_http_port = "8080"
        trust_domain = {{ .Values.general.trustDomain | quote }}
        plugin_dir = "conf/server/plugin"
        log_level = {{ .Values.general.logLevel | quote}}
        base_svid_ttl = {{ .Values.general.baseSvidTtl }}
        server_svid_ttl = {{ .Values.general.serverSvidTtl }}
        umask = ""
    }
{{ tpl .Values.server.pluginConfig . | indent 4 }}