apiVersion: v1
kind: Service
metadata:
  name: {{ template "server.spire.fullname" . }}
  labels:
    app: {{ template "spire.name" . }}
    component: server
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: bind
      protocol: TCP
      name: bind
  selector:
    app: {{ template "spire.name" . }}
    component: server
    release: {{ .Release.Name }}
