apiVersion: v1
kind: Secret
metadata:
  name: {{ template "server.spire.fullname" . }}
  labels:
    app: {{ template "spire.name" . }}
    component: server
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  upstream_ca.crt: {{ .Values.upstreamCa.cert | b64enc | quote}}
  upstream_ca.key: {{ .Values.upstreamCa.key | b64enc | quote }}