version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: build docker image
          command: docker build -t eicnix/spire docker/
